package com.example.worsi_backend.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.InitializingBean;
import org.springframework.jdbc.core.JdbcTemplate;

import javax.sql.DataSource;
import java.util.List;

/**
 * Safety net for the forgot-password schema. Runs BEFORE Hibernate validates the schema (see
 * PasswordResetSchemaConfig) and idempotently creates password_reset_tokens and
 * users.password_changed_at if they are missing. Every statement uses IF NOT EXISTS and mirrors
 * db/migration/V2__add_password_reset.sql exactly, so it is harmless when Flyway has already
 * applied that migration (and Flyway is equally happy if this ran first).
 */
public class PasswordResetSchemaInitializer implements InitializingBean {

    private static final Logger log = LoggerFactory.getLogger(PasswordResetSchemaInitializer.class);

    private static final List<String> STATEMENTS = List.of(
            "CREATE TABLE IF NOT EXISTS password_reset_tokens ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE, "
                    + "token_hash VARCHAR(64) NOT NULL, "
                    + "expires_at TIMESTAMP NOT NULL, "
                    + "used BOOLEAN NOT NULL DEFAULT FALSE, "
                    + "created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                    + "CONSTRAINT uk_password_reset_tokens_token_hash UNIQUE (token_hash))",
            "CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_user_created "
                    + "ON password_reset_tokens (user_id, created_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_expires_at "
                    + "ON password_reset_tokens (expires_at)",
            "ALTER TABLE users ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMP"
    );

    private final JdbcTemplate jdbc;

    public PasswordResetSchemaInitializer(DataSource dataSource) {
        this.jdbc = new JdbcTemplate(dataSource);
    }

    @Override
    public void afterPropertiesSet() {
        for (String sql : STATEMENTS) {
            try {
                jdbc.execute(sql);
            } catch (Exception e) {
                // e.g. the "users" table does not exist yet on a brand-new database (Flyway/V1 owns that).
                log.warn("Password-reset schema step skipped: {}", e.getMessage());
            }
        }
        log.info("Password-reset schema check completed.");
    }
}
