-- Forgot-password / reset-password support.
--
-- 1) password_reset_tokens: one row per reset link that was emailed. Only the SHA-256 hash of the
--    token is stored (never the raw token), so a database leak cannot be used to reset accounts.
-- 2) users.password_changed_at: stamped whenever a password is reset. The JWT filter rejects any
--    JWT issued before this moment, which is how existing sessions are signed out after a reset
--    (the app's JWTs are stateless, so there is nothing else to "delete").

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash  VARCHAR(64)  NOT NULL,
    expires_at  TIMESTAMP    NOT NULL,
    used        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_password_reset_tokens_token_hash UNIQUE (token_hash)
);

CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_user_created
    ON password_reset_tokens (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_expires_at
    ON password_reset_tokens (expires_at);

-- Nullable on purpose: NULL means "password never reset", so every existing user/JWT is unaffected.
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMP;
