spring.application.name=worsi-backend
server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/worksy}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0

# JWT
app.jwt.secret=${JWT_SECRET:worsi-dev-only-secret-key-change-me-0123456789}

# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}

# Google OAuth
app.oauth.google.client-id=918448887306-hi6h0phgpefv2iv3r3d64gf61vdhf8tn.apps.googleusercontent.com


# Phone OTP
app.otp.expiry-minutes=${OTP_EXPIRY_MINUTES:5}
app.otp.max-requests-per-window=${OTP_MAX_REQUESTS_PER_WINDOW:5}
app.otp.request-window-minutes=${OTP_REQUEST_WINDOW_MINUTES:15}
app.otp.resend-cooldown-seconds=${OTP_RESEND_COOLDOWN_SECONDS:30}
app.otp.max-verify-attempts=${OTP_MAX_VERIFY_ATTEMPTS:5}

# SMS Provider
app.sms.provider=${SMS_PROVIDER:console}

# Forgot Password / Reset Password
app.frontend.base-url=${FRONTEND_BASE_URL:http://localhost:3000}
app.password-reset.expiry-minutes=${PASSWORD_RESET_EXPIRY_MINUTES:30}
app.password-reset.cooldown-seconds=${PASSWORD_RESET_COOLDOWN_SECONDS:60}
app.password-reset.max-requests-per-window=${PASSWORD_RESET_MAX_REQUESTS_PER_WINDOW:3}
app.password-reset.request-window-minutes=${PASSWORD_RESET_REQUEST_WINDOW_MINUTES:60}

# Gmail SMTP
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false
# Email Provider
app.mail.provider=${MAIL_PROVIDER:smtp}

# Email Sender
app.mail.from=${MAIL_FROM}